matrix:
  include:
    # - os: linux
    #   compiler: clang
    #   language: cpp
    #   dist: trusty or bionic

    - os: windows
      compiler: clang
      language: cpp

    - os: osx
      language: objective-c
      compiler: clang
      osx_image: xcode12.2

      addons:
        homebrew:
          packages:
          - cmake
          update: true

# do the build
script:
- if [ $TRAVIS_OS_NAME == osx ]; then ./scripts/cibuild.sh $TRAVIS_OS_NAME; fi
- if [ $TRAVIS_OS_NAME == windows ]; then ./scripts/cibuild.sh $TRAVIS_OS_NAME; fi
#- if [ $TRAVIS_OS_NAME == linux ]; then ./scripts/cibuild.sh $TRAVIS_OS_NAME; fi

# deploy bin folder to releases on github
deploy:
  - provider: releases
    api_key:
      secure: $GITHUB_TOKEN
    file_glob: true
    file: bin/*
    skip_cleanup: true
    keep_history: true
    #draft: true
    #prerelease: true
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = windows
      #branch: master
     
  - provider: releases
    api_key:
      secure: $GITHUB_TOKEN
    file_glob: true
    file: bin/*
    skip_cleanup: true
    keep_history: true
    #draft: true
    #prerelease: true
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = osx
      # branch: master
