os: osx
osx_image: xcode12.2
compiler: clang
language: cpp

# need cmake 3.19 for universal apps, but vms have 3.18
addons:
  homebrew:
    packages:
    - cmake
    update: true

script:
- if [ $TRAVIS_OS_NAME == osx ]; then ./scripts/cibuild.sh; fi
