name: "tagged-release"

# run on any changes tagged with v*, will copy data to releases
on:
  push:
    tags:
      - 'v*'

jobs:
  tagged-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        os: [macos-latest, windows-latest]
        
    steps:
      - name: Update CMake
        uses: lukka/get-cmake@latest

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build and install to bin/
        run: ./scripts/cibuild.sh ${{ matrix.os }}
        shell: bash

      # this doesn't work with a matrix, only macos is uploaded, no way to specify same tag  
      - name: Upload build to releases
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: bin/*.zip

      # so do another upload to get both
      - name: Upload all builds to releases
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/*.zip
          file_glob: true
          tag: ${{ github.ref }}
