name: "tagged-release"

# run on any changes tagged with v*, will copy data to releases
on:
  push:
    tags:
      - 'v*'

jobs:
  tagged-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        os: [macos-latest, windows-latest]

    steps:
      - name: Update CMake 
        uses: lukka/get-cmake@latest 

      - name: Check out code 
        uses: actions/checkout@v2

      - name: Build and install to bin/ 
        run: ./scripts/cibuild.sh ${{ matrix.os }}
        shell: bash
          
      - name: Upload build to releases
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          draft: false
          files: |
            README.md
            LICENSE.txt
            bin/*